In [3]:
import numpy as np

## Numpy Arrays

##### A. Arrays

In [11]:
arr = np.array([1, 2, 3], dtype=np.int32)
print(arr)
print(repr(arr))

[1 2 3]
array([1, 2, 3], dtype=int32)


##### B. Copying in numpy 

In [6]:
a = np.array([1, 2])
b = np.array([9, 10])
c = a
c[0] = 100
print('a', a)
print('c', c)

d = b.copy()
d[0] = 100
print('b', b)
print('d', d)

a [100   2]
c [100   2]
b [ 9 10]
d [100  10]


##### C. Casting

In [9]:
arr = np.array([0, 1, 2])
print(arr.dtype)
print(arr)
arr = arr.astype(np.float32)
print(arr.dtype)
print(arr)

int64
[0 1 2]
float32
[0. 1. 2.]


##### D. NaN

In [14]:
arr = np.array([np.nan, 1, 2])
print(repr(arr))

arr = np.array([np.nan, 'abc'])
print(repr(arr))

# Will result in a ValueError
np.array([np.nan, 1, 2], dtype=np.int32)

array([nan,  1.,  2.])
array(['nan', 'abc'], dtype='<U32')


ValueError: cannot convert float NaN to integer

##### E. Infinity

In [18]:
print(np.inf > 1000000)

arr = np.array([np.inf, 5])
print(repr(arr))

arr = np.array([-np.inf, 1])
print(repr(arr))

# Will result in an OverflowError
np.array([np.inf, 3], dtype=np.int32)

True
array([inf,  5.])
array([-inf,   1.])


OverflowError: cannot convert float infinity to integer

## Numpy Basics

##### A. Ranged Data

In [25]:
arr = np.arange(5)
print(repr(arr))

arr = np.arange(5, dtype=np.float32)
print(repr(arr))

arr = np.arange(5.1)
print(repr(arr))

arr = np.arange(5.2)
print(repr(arr))

arr = np.arange(-1, 4)
print(repr(arr))

arr = np.arange(-1.5, 4, 2)
print(repr(arr))

array([0, 1, 2, 3, 4])
array([0., 1., 2., 3., 4.], dtype=float32)
array([0., 1., 2., 3., 4., 5.])
array([0., 1., 2., 3., 4., 5.])
array([-1,  0,  1,  2,  3])
array([-1.5,  0.5,  2.5])


In [29]:
# End of the range is inclusive
arr = np.linspace(1, 4, num=4, dtype=np.int32)
print(repr(arr))

arr = np.linspace(1, 4, num=4)
print(repr(arr))

# To make end of the range exclusive
arr = np.linspace(1, 4, num=4, endpoint=False)
print(repr(arr))

array([1, 2, 3, 4], dtype=int32)
array([1., 2., 3., 4.])
array([1.  , 1.75, 2.5 , 3.25])


##### B. Reshaping

In [32]:
arr = np.arange(8)

reshaped_arr = np.reshape(arr, (2, 4))
print(repr(reshaped_arr))
print('New shape: {}'.format(reshaped_arr.shape))

# -1 is allowed in only one of the arguments in reshape. It will take necessary value to allow all elements
reshaped_arr = np.reshape(arr, (-1, 2, 2))
print(repr(reshaped_arr))
print('New shape: {}'.format(reshaped_arr.shape))

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])
New shape: (2, 4)
array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])
New shape: (2, 2, 2)


In [34]:
arr = np.arange(8)
arr = np.reshape(arr, (2, 4))
flattened = arr.flatten()
print(repr(arr))
print('arr shape: {}'.format(arr.shape))
print(repr(flattened))
print('flattened shape: {}'.format(flattened.shape))

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])
arr shape: (2, 4)
array([0, 1, 2, 3, 4, 5, 6, 7])
flattened shape: (8,)


##### C. Transposing

In [36]:
arr = np.arange(8)
arr = np.reshape(arr, (4, 2))
transposed = np.transpose(arr)
print(repr(arr))
print('arr shape: {}'.format(arr.shape))
print(repr(transposed))
print('transposed shape: {}'.format(transposed.shape))

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])
arr shape: (4, 2)
array([[0, 2, 4, 6],
       [1, 3, 5, 7]])
transposed shape: (2, 4)


In [38]:
arr = np.arange(24)
arr = np.reshape(arr, (3, 4, 2))
# 3 is at 0 index, 4 is at 1 index and 2 is at 3 index.
# axes 1, 2, 0 means new dimessions are (4, 2, 3). Values at particlar index are positioned here.
transposed = np.transpose(arr, axes=(1, 2, 0))
print('arr shape: {}'.format(arr.shape))
print('transposed shape: {}'.format(transposed.shape))

arr shape: (3, 4, 2)
transposed shape: (4, 2, 3)


##### D. Zeros and Ones

In [40]:
arr = np.zeros(4)
print(repr(arr))

arr = np.ones((2, 3))
print(repr(arr))

arr = np.ones((2, 3), dtype=np.int32)
print(repr(arr))

array([0., 0., 0., 0.])
array([[1., 1., 1.],
       [1., 1., 1.]])
array([[1, 1, 1],
       [1, 1, 1]], dtype=int32)


In [43]:
arr = np.array([[1, 2], [3, 4]])
print(repr(np.zeros_like(arr)))

arr = np.array([[0., 1.], [1.2, 4.]])
print(repr(np.ones_like(arr)))
print(repr(np.ones_like(arr, dtype=np.int32)))

array([[0, 0],
       [0, 0]])
array([[1., 1.],
       [1., 1.]])
array([[1, 1],
       [1, 1]], dtype=int32)


## Math

##### A. Arithmetic

In [44]:
arr = np.array([[1, 2], [3, 4]])
# Add 1 to element values
print(repr(arr + 1))
# Subtract element values by 1.2
print(repr(arr - 1.2))
# Double element values
print(repr(arr * 2))
# Halve element values
print(repr(arr / 2))
# Integer division (half)
print(repr(arr // 2))
# Square element values
print(repr(arr**2))
# Square root element values
print(repr(arr**0.5))

array([[2, 3],
       [4, 5]])
array([[-0.2,  0.8],
       [ 1.8,  2.8]])
array([[2, 4],
       [6, 8]])
array([[0.5, 1. ],
       [1.5, 2. ]])
array([[0, 1],
       [1, 2]])
array([[ 1,  4],
       [ 9, 16]])
array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])


def f2c(temps):
  return (5/9)*(temps-32)

fahrenheits = np.array([32, -4, 14, -40, 80])
celsius = f2c(fahrenheits)
print('Celsius: {}'.format(repr(celsius)))

##### B. Non-linear functions

In [48]:
arr = np.array([[1, 2], [3, 4]])
# Raised to power of e
print(repr(np.exp(arr)))
# Raised to power of 2
print(repr(np.exp2(arr)))

arr2 = np.array([[1, 10], [np.e, np.pi]])
# Natural logarithm
print(repr(np.log(arr2)))
# Base 10 logarithm
print(repr(np.log10(arr2)))

array([[ 2.71828183,  7.3890561 ],
       [20.08553692, 54.59815003]])
array([[ 2.,  4.],
       [ 8., 16.]])
array([[0.        , 2.30258509],
       [1.        , 1.14472989]])
array([[0.        , 1.        ],
       [0.43429448, 0.49714987]])


In [52]:
arr = np.array([[1, 2], [3, 4]])

# Raise 3 to power of each number in arr
print(repr(np.power(3, arr)))

arr2 = np.array([[10.2, 4], [3, 5]])
# Raise arr2 to power of each number in arr
print(repr(np.power(arr2, arr)))

array([[ 3,  9],
       [27, 81]])
array([[ 10.2,  16. ],
       [ 27. , 625. ]])


##### C. Matrix multiplication
Since NumPy arrays are basically vectors and matrices, it makes sense that there are functions for dot products and matrix multiplication. Specifically, the main function to use is np.matmul, which takes two vector/matrix arrays as input and produces a dot product or matrix multiplication.

The code below shows various examples of matrix multiplication. When both inputs are 1-D, the output is the dot product.

Note that the dimensions of the two input matrices must be valid for a matrix multiplication. Specifically, the second dimension of the first matrix must equal the first dimension of the second matrix, otherwise np.matmul will result in a ValueError.

In [54]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([-3, 0, 10])
print(np.matmul(arr1, arr2))

27


In [55]:
arr3 = np.array([[1, 2], [3, 4], [5, 6]])
arr4 = np.array([[-1, 0, 1], [3, 2, -4]])
print(repr(np.matmul(arr3, arr4)))
print(repr(np.matmul(arr4, arr3)))

array([[  5,   4,  -7],
       [  9,   8, -13],
       [ 13,  12, -19]])
array([[  4,   4],
       [-11, -10]])


## Random

##### A. Random Integers

In [107]:
print(np.random.randint(5))
print(np.random.randint(5))
print(np.random.randint(5, high=6))
random_arr = np.random.randint(-3, high=14, size=(2, 2))
print(repr(random_arr))

0
0
5
array([[-2,  9],
       [ 4, 10]])


##### B. Utility functions

In [118]:
np.random.seed(1)
print(np.random.randint(100))
random_arr = np.random.randint(3, high=100, size=(2, 2))
print(repr(random_arr))

# New seed
np.random.seed(2)
print(np.random.randint(10))
random_arr = np.random.randint(3, high=100,
                               size=(2, 2))
print(repr(random_arr))

# Original seed
np.random.seed(1)
print(np.random.randint(10))
random_arr = np.random.randint(3, high=100,
                               size=(2, 2))
print(repr(random_arr))

37
array([[15, 75],
       [12, 78]])
8
array([[18, 75],
       [25, 46]])
5
array([[15, 75],
       [12, 78]])


The np.random.shuffle function allows us to randomly shuffle an array. Note that the shuffling happens in place (i.e. no return value), and shuffling multi-dimensional arrays only shuffles the first dimension.

The code below shows example usages of np.random.shuffle. Note that only the rows of matrix are shuffled (i.e. shuffling along first dimension only).

In [119]:
vec = np.arange(1, 6)
np.random.shuffle(vec)
print(repr(vec))
np.random.shuffle(vec)
print(repr(vec))

matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
np.random.shuffle(matrix)
print(repr(matrix))

array([3, 4, 2, 5, 1])
array([5, 3, 4, 2, 1])
array([[4, 5, 6],
       [7, 8, 9],
       [1, 2, 3]])


##### C. Distributions

In [128]:
print(np.random.uniform())
print(np.random.uniform(low=-1.5, high=2.2))
print(repr(np.random.uniform(size=3)))
print(repr(np.random.uniform(low=-3.4, high=5.9, size=(2, 2))))

0.5843891207379291
0.5938745016175146
array([0.61393832, 0.95653566, 0.26097898])
array([[-1.25155657,  1.56107096],
       [ 5.43442469,  1.18545422]])


In [133]:
print(np.random.normal())
print(np.random.normal(loc=1.5, scale=3.5))
print(repr(np.random.normal(loc=-2.4, scale=4.0, size=(2, 2))))

1.015262918840633
4.858728715673602
array([[ -2.90921259,   0.39421666],
       [-11.30198034,  -7.4729174 ]])


##### D. Custom Sampling

In [2]:
colors = ['red', 'blue', 'green']
print(np.random.choice(colors))
print(repr(np.random.choice(colors, size=2)))
print(repr(np.random.choice(colors, size=(2, 3), p=[.8, .19, .01])))

red
array(['red', 'blue'], dtype='<U5')
array([['red', 'red', 'red'],
       ['red', 'red', 'red']], dtype='<U5')


## Indexing

##### 1. Array Accessing

In [5]:
arr = np.array([1, 2, 3, 4, 5])
print(arr[0])
print(arr[4])

arr = np.array([[6, 3], [0, 2]])
# Subarray
print(repr(arr[0]))

1
5
array([6, 3])


##### 2. Slicing

In [12]:
arr = np.array([1, 2, 3, 4, 5])
print(repr(arr[:]))
print(repr(arr[1:]))
print(repr(arr[2:4]))
print(repr(arr[:-1]))
print(repr(arr[-2:]))

array([1, 2, 3, 4, 5])
array([2, 3, 4, 5])
array([3, 4])
array([1, 2, 3, 4])
array([4, 5])


In [19]:
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])
print(repr(arr[:]))
print(repr(arr[1:]))

# Last item in all rows
print(repr(arr[:, -1]))

print(repr(arr[:, 1:]))
print(repr(arr[0:1, 1:]))
print(repr(arr[0, 1:]))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])
array([[4, 5, 6],
       [7, 8, 9]])
array([3, 6, 9])
array([[2, 3],
       [5, 6],
       [8, 9]])
array([[2, 3]])
array([2, 3])


##### C. Argmin and argmax

In [21]:
arr = np.array([[-2, -1, -3],
                [4, 5, -6],
                [-3, 9, 1]])
print(np.argmin(arr[0]))
print(np.argmax(arr[2]))
print(np.argmin(arr))

2
1
5


In [22]:
arr = np.array([[-2, -1, -3],
                [4, 5, -6],
                [-3, 9, 1]])
print(repr(np.argmin(arr, axis=0)))
print(repr(np.argmin(arr, axis=1)))
print(repr(np.argmax(arr, axis=-1)))

array([2, 0, 1])
array([2, 2, 0])
array([1, 1, 1])
